import sys


def error_and_exit(msg):
    print(msg)
    sys.exit(1)
